# Generated by Django 3.1.5 on 2021-01-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='updated',
            new_name='_updated',
        ),
        migrations.AddField(
            model_name='post',
            name='down_votes',
            field=models.ManyToManyField(related_name='down_voted_posts', to='api.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='up_votes',
            field=models.ManyToManyField(related_name='up_voted_posts', to='api.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='down_votes',
            field=models.ManyToManyField(related_name='down_voted_projects', to='api.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='up_votes',
            field=models.ManyToManyField(related_name='up_voted_projects', to='api.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', to='api.User'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='down_votes',
            field=models.ManyToManyField(related_name='down_voted_comments', to='api.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='up_votes',
            field=models.ManyToManyField(related_name='up_voted_comments', to='api.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.user'),
        ),
    ]
