# Generated by Django 3.1.5 on 2021-02-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210201_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='down_votes',
            new_name='downvoted_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='up_votes',
            new_name='upvoted_by',
        ),
    ]
